name: Automated tests

on:
  workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Set up secrets
        env:
          ENV__API__OPERATORS__OPERATOR_TOKEN: ${{ secrets.ENV__API__OPERATORS__OPERATOR_TOKEN }}
          ENV__API__COMPANY__COMPANY_TOKEN: ${{ secrets.ENV__API__COMPANY__COMPANY_TOKEN }}
        run: |
          echo "ENV__API__OPERATORS__OPERATOR_TOKEN=${{ secrets.ENV__API__OPERATORS__OPERATOR_TOKEN }}" >> config/local.env
          echo "ENV__API__COMPANY__COMPANY_TOKEN=${{ secrets.ENV__API__COMPANY__COMPANY_TOKEN }}" >> config/local.env

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest -v tests/sms_push_reader/test_sms_reader.py::test_sms_reader
