name: Automated tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default: second_test
        type: choice
        options:
          - first_test
          - second_test

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Set up secrets
        env:
          ENV__API__BASE_HOST: ${{ secrets.ENV__API__BASE_HOST }}
          ENV__API__OPERATORS__USER_NAME: ${{ secrets.ENV__API__OPERATORS__USER_NAME }}
          ENV__API__OPERATORS__OPERATOR_TOKEN: ${{ secrets.ENV__API__OPERATORS__OPERATOR_TOKEN }}
        run: |
          echo "ENV__API__BASE_HOST=${{ secrets.ENV__API__BASE_HOST }}" >> config/local.env
          echo "ENV__API__OPERATORS__USER_NAME=${{ secrets.ENV__API__OPERATORS__USER_NAME }}" >> config/local.env
          echo "ENV__API__OPERATORS__OPERATOR_TOKEN=${{ secrets.ENV__API__OPERATORS__OPERATOR_TOKEN }}" >> config/local.env

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest -v tests/test_actions_env.py::test_show_env
